/**
 * Theme color names accepted by HeroUI's useThemeColor hook.
 * Extracted from heroui-native's THEME_COLORS constant.
 */
export type ThemeColor =
  | "background"
  | "foreground"
  | "surface"
  | "surface-foreground"
  | "surface-hover"
  | "overlay"
  | "overlay-foreground"
  | "muted"
  | "accent"
  | "accent-foreground"
  | "segment"
  | "segment-foreground"
  | "border"
  | "separator"
  | "focus"
  | "link"
  | "default"
  | "default-foreground"
  | "success"
  | "success-foreground"
  | "warning"
  | "warning-foreground"
  | "danger"
  | "danger-foreground"
  | "field"
  | "field-foreground"
  | "field-placeholder"
  | "field-border"
  | "background-secondary"
  | "background-tertiary"
  | "background-inverse"
  | "default-hover"
  | "accent-hover"
  | "success-hover"
  | "warning-hover"
  | "danger-hover"
  | "accent-soft"
  | "accent-soft-foreground"
  | "danger-soft"
  | "danger-soft-foreground"
  | "success-soft"
  | "success-soft-foreground"
  | "warning-soft"
  | "warning-soft-foreground"
  | "surface-secondary"
  | "surface-tertiary"
  | "border-secondary"
  | "border-tertiary";
