blank_issues_enabled: false
contact_links:
  - name: Support & Questions
    url: https://discord.gg/pRYNYr4W5A
    about: Need help? Having trouble setting up? Reach out to the Actual Budget community on Discord.
